version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx-single
    hostname: nginx-single
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./certs:/etc/nginx/certs
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
